"""
Text Removal using Gemini Image Inpainting
===========================================
Uses the binary mask from run_pipeline_pro.py to remove text from images.
Requires: gemini-2.0-flash-exp (image generation model)
"""

import os
import argparse
import json
from pathlib import Path
import cv2
import numpy as np
from google import genai
from google.genai import types
from PIL import Image
from dotenv import load_dotenv

load_dotenv()

# --------------------------------------------------
# CONFIG
# --------------------------------------------------

MODEL_NAME = "gemini-3-pro-image-preview"  # Image generation model
API_KEY = os.getenv("GEMINI_API_KEY")

client = genai.Client(api_key=API_KEY)

# --------------------------------------------------
# SYSTEM INSTRUCTION (AUTHORITATIVE)
# --------------------------------------------------

SYSTEM_INSTRUCTION = """
You are a deterministic image editing system.

You must strictly remove ALL visual content inside the provided mask.
The mask is authoritative and must be followed exactly.

You are NOT allowed to preserve or reinterpret masked content.
If any text, symbol, or mark appears inside the mask, it must be removed.

You must preserve all unmasked regions exactly as they are.
No creativity is allowed.
"""

# --------------------------------------------------
# MAIN PROMPT
# --------------------------------------------------

PROMPT = """
I am providing two images:
1. First image: The original photograph
2. Second image: A binary mask where WHITE areas = text to REMOVE, BLACK areas = preserve

Your task:
- Remove ALL content that appears in WHITE masked areas from the original image
- Fill removed areas naturally using surrounding background context
- Do NOT modify any content in BLACK (unmasked) areas
- Preserve all details outside the white mask exactly
- Do NOT remove logos, symbols, or objects that are NOT covered by white mask

Return only the edited image with text removed.
"""


def remove_text(pipeline_output_dir: str, output_name: str = "inpainted.png"):
    """
    Remove text from image using the mask generated by run_pipeline_pro.py
    
    Args:
        pipeline_output_dir: Path to pipeline output folder (e.g., pipeline_outputs/run_XXXX_pro)
        output_name: Name of the output inpainted image
    """
    pipeline_dir = Path(pipeline_output_dir)
    
    # Load final_result_pro.json to get original image path
    json_path = pipeline_dir / "final_result_pro.json"
    if not json_path.exists():
        print(f"Error: {json_path} not found")
        return
    
    with open(json_path, "r") as f:
        data = json.load(f)
    
    original_image_path = data["image"]
    mask_path = pipeline_dir / "text_mask.png"
    
    if not Path(original_image_path).exists():
        print(f"Error: Original image not found at {original_image_path}")
        return
    
    if not mask_path.exists():
        print(f"Error: Text mask not found at {mask_path}")
        return
    
    print(f"Original image: {original_image_path}")
    print(f"Text mask: {mask_path}")
    
    # --------------------------------------------------
    # LOAD IMAGES
    # --------------------------------------------------
    
    image = Image.open(original_image_path).convert("RGBA")
    
    # Load mask and DILATE it (CRAFT masks are too thin for inpainting)
    mask_cv = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
    kernel = np.ones((3, 3), np.uint8)
    mask_dilated = cv2.dilate(mask_cv, kernel, iterations=2)
    
    # Save dilated mask for reference
    dilated_mask_path = pipeline_dir / "text_mask_dilated.png"
    cv2.imwrite(str(dilated_mask_path), mask_dilated)
    print(f"Dilated mask saved: {dilated_mask_path}")
    
    # Convert to PIL Image for Gemini
    mask = Image.fromarray(mask_dilated)
    
    print(f"Image size: {image.size}")
    print(f"Mask size: {mask.size}")
    
    # --------------------------------------------------
    # GEMINI API CALL FOR INPAINTING
    # --------------------------------------------------
    
    print(f"\nCalling {MODEL_NAME} for text removal...")
    
    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=[
                PROMPT,
                image,
                mask  # Pass mask as second image
            ],
            config=types.GenerateContentConfig(
                temperature=0,
                response_modalities=["image"]
            )
        )
        
        # --------------------------------------------------
        # EXTRACT AND SAVE RESULT
        # --------------------------------------------------
        
        # Look for image in response parts
        result_image = None
        for part in response.candidates[0].content.parts:
            if hasattr(part, 'inline_data') and part.inline_data:
                # Extract image data
                import base64
                from io import BytesIO
                
                image_data = part.inline_data.data
                result_image = Image.open(BytesIO(image_data))
                break
            elif hasattr(part, 'image'):
                result_image = part.image
                break
        
        if result_image:
            output_path = pipeline_dir / output_name
            result_image.save(output_path)
            print(f"\n✅ Text removal complete: {output_path}")
            return str(output_path)
        else:
            print("Warning: No image in response. Response text:")
            for part in response.candidates[0].content.parts:
                if hasattr(part, 'text'):
                    print(part.text)
            return None
            
    except Exception as e:
        print(f"Error during inpainting: {e}")
        return None


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Remove text from image using Gemini inpainting")
    parser.add_argument(
        "pipeline_dir",
        nargs="?",
        default="pipeline_outputs/run_1766739537_pro",
        help="Path to pipeline output directory containing text_mask.png"
    )
    parser.add_argument(
        "--output",
        default="inpainted.png",
        help="Output filename (default: inpainted.png)"
    )
    
    args = parser.parse_args()
    
    remove_text(args.pipeline_dir, args.output)
